### ISSUE TITLE
Using Roots with Pods

### ISSUE THREAD

**Issue by Jorenm** [roots/sage#1129]
There seems to be an issue with using these together. Pods uses template_redirect, which prevents template_include from ever firing, which causes the base.php file to not be used.

**Comment by sc0ttkclark** [comment]
Just following up here

1. Providing the template name in `template_include` is too late because Sage has already figured out what template location (full path) to use based on the postdata set up
2. Filtering before Sage's `template_include` hook won't evaluate the template file to the correct full path it expects
3. Since many people are using Pods Pages (custom URL routing) with content types that aren't post types, such as Advanced Content Types (custom solo tables in Pods) -- Sage throws errors when it's a 404 page but it expects post data to come through

I'll continue working on solutions for this and submit any bugs I can in Sage/Acorn regarding this functionality we hope to bring compatibility for between Sage/Pods.
