### ISSUE TITLE
Latest posts not showing on homepage?

### ISSUE THREAD

**Issue by jimmyjamieson** [roots/sage#1399]
I've just downloaded this to give it a try. I've semi-converted an older theme over, but I can't seem to show the latest posts on the homepage. The correct option is set in admin and there's no custom homepage, but nothing.

Is this a bug or am I missing something? I don't see anything in your docs.

**Comment by Foxaii** [comment]
We haven't done anything to modify how recent posts are shown.

You may have done something during your semi-conversion, so can you please try again with an unmodified Sage install, and again with an unmodified default theme (any of the twenty somethings).

If the issue is reproduced in Sage but not the default theme we'll keep this issue open. In any other event you should close this and head over to https://discourse.roots.io/ for support from the community.

Thanks.

**Comment by jimmyjamieson** [comment]
I replaced the origin index.php with one directly from github, and that seems to have fixed it :)
