### ISSUE TITLE
PHP 5.3 array syntax issue

### ISSUE THREAD

**Issue by a-r-d** [roots/sage#1413]
Roots could easily run on PHP 5.3 if all of the array literal shorthand syntax was changed (i.e. "array()" vs "[]" mentioned [here](http://php.net/manual/en/migration54.new-features.php). In fact I have performed this downgrade due to a client's web host only supporting PHP 5.3. This is the only incompatibility I have found.

If I make these changes and submit a pull request will it be accepted? I see no reason for the exclusion of PHP 5.3 support over a simple syntax shorthand issue but I understand people can become very picky about these seemingly trivial issues.

**Comment by swalkinshaw** [comment]
A PR would not be accepted for this.

It was a deliberate decision on our part and that won't be changing. 5.3 is an unsupported version of PHP since August 2014. 5.4 won't even be supported past September.

It's been **3 years** since 5.4 came out. This is not a trivial issue at all. It's a pretty serious one in our opinion.

See also https://discourse.roots.io/t/what-are-my-options-if-the-server-cant-be-upgraded-to-5-4/3259/2?u=swalkinshaw

**Comment by a-r-d** [comment]
Ok got it, I understand your position. I will put up a fork that is 5.3 compatible for anyone interested because it was time consuming to change all of the syntax.

**Comment by retlehs** [comment]
move the web forward, man.

>  In fact I have performed this downgrade due to a client's web host only supporting PHP 5.3. 

do your client a favor and get them on a better host.
