### ISSUE TITLE
Change hardcoded `/` to OS directory separator

### ISSUE THREAD

**Issue by austinpray** [roots/sage#1483]
https://github.com/roots/sage/blob/71c2e78b0e42c1a86adba8d4a30e1b6d9df17dff/lib/assets.php#L52

I want to change the hardcoded `/` to `DIRECTORY_SEPARATOR`. PHP folks: is this a good idea?

**Comment by MikeiLL** [comment]
Strikes me as a worthwhile abstraction.

**Comment by QWp6t** [comment]
That would be bonkers because `asset_path()` is supposed to return a URL.

But even if that was for file system stuff, it would still be unnecessary. Windows hasn't shit its pants at `/` in over 10 years.

`DIRECTORY_SEPARATOR` is useful if you're working with values returned by the OS or some such. Like if you're reading an envar or parsing `realpath()` or something. Other than that, just use `/` and you'll be fine.

**Comment by austinpray** [comment]
Oh duh.
