### ISSUE TITLE
Call to undefined function get_template_part()

### ISSUE THREAD

**Issue by Tasemu** [roots/sage#1489]
PHP Fatal error:  Call to undefined function get_template_part() in /var/www/public/wp-content/themes/digit/index.php on line 1

Hey guys, I am getting this error in my php error logs. I have a feeling it is also messing with my javascript because I am queueing them up correctly. I have queued jQuery, following by Owl Carousel and then main.js. However it is throwing me a javascript error saying this:

Uncaught TypeError: t(...).owlCarousel is not a function

I'm completely beat, been trying to work this out for hours and have gotten nowhere. Cant keep workin on my theme until it is resolved. Anyone had this issue?

**Comment by QWp6t** [comment]
Something is loading `/wp-content/themes/digit/index.php` without first loading WordPress. This is why many themes will put something like `defined('ABSPATH') || exit;` in the top of their theme files.

If you're still having issues, start a thread on [our forums](https://discourse.roots.io) or [stackexchange](http://wordpress.stackexchange.com/) since this isn't a Sage issue.
