### ISSUE TITLE
Error thrown when including hooks/filters inside lib

### ISSUE THREAD

**Issue by acha5066** [roots/sage#1506]
I'm trying to include a filter to change the class of previous posts links. If I call this in the functions.php file it works as expected. However, if I call it in lib/extras.php or any other file where it is supposed to be called it throws an error (see below).
```
add_filter('next_posts_link_attributes', 'posts_link_attributes');
add_filter('previous_posts_link_attributes', 'posts_link_attributes');

function posts_link_attributes() {
    return 'class="button"';
}
```
```
Warning: call_user_func_array() expects parameter 1 to be a valid callback, function 'posts_link_attributes' not found or invalid function name in /Applications/MAMP/htdocs/site/htdocs/wp-includes/plugin.php on line 213
```
Why is this happening? Am I calling the filter in the correct place in extras.php?

**Comment by aaemnnosttv** [comment]
You're registering your callback there as if the function is in the global namespace.  `lib/extras.php` uses the `Roots\Sage\Extras` namespace.  That's why the same code works in `functions.php` which has no namespace of its own.

For that code to work in extras, you need to register the callback function using the fully-qualified function name, like so:
```php
add_filter('next_posts_link_attributes', __NAMESPACE__ . '\\posts_link_attributes');
// or this would work just fine as well, if you find it more readable
add_filter('previous_posts_link_attributes', 'Roots\\Sage\\Extras\\posts_link_attributes');
```

If you're new to this whole concept, you may want to [read up on it here](http://php.net/manual/en/language.namespaces.php).

Another alternative would be using a simple closure instead of a named function for the callback, which wouldn't require any funny namespace business.  It's really up to you to decide what's right for your project!

**Comment by acha5066** [comment]
Makes sense. Cheers for the link I will read up on it!
