### ISSUE TITLE
Document and list workarounds about 'npm install' failing on windows due to long pathnames

### ISSUE THREAD

**Issue by henrify** [roots/sage#1548]
It looks like Sage has so deep dependency tree that it hits the windows file/directory name limits if the theme is placed in a typical location (e.g. /projects/www.blaahblaah.com/wp-content/themes/blaahblaah).

This is not your fault and it has been much discussed in node/npm forums.

Still, you probably have high proportion of users who are new to npm, and this gives them horrible new starter experience -- specially considering that Sage is a "starter" theme and aims to reduce initial setup time.

The issue is likely to be so common that it should be documented clearly in e.g "https://roots.io/sage/docs/theme-development-and-building/" and with clear workarounds (e.g. moving the specific theme directory temporarily to root and running npm from there, or symlinking).

**Comment by austinpray** [comment]
Have you tried npm 3? Does it help any?

**Comment by henrify** [comment]
I'm unfortunately not able to upgrade for testing, because I also do node.js development and npm 3 is too early version (i believe it was released only about week ago).

I had run into the too-long-filenames before and I was able to work around it quickly, so the purpose of this issue is not to seek help, but to make sure that your other users don't get hit by it.

**Comment by chrisatomix** [comment]
I've had to setup 4 developers with the Sage build tools, and we're all using Windows. It would be handy to have some basic documentation for Windows developers listing the common pitfalls that could come up ('rimraf' is a very handy package!).

I've just upgraded to NPM 3 and had all kinds of trouble, there were some packages which didn't seem to like the flat folder structure (I even had issues with Bower). Everything is now running smoothly again with NPM 2.14.4 and Node 4.1.2.

I'll try upgrading again once NPM 3 has stabilized a bit more and all the packages are fully compatible. I'm hoping this will resolve most of the Windows-specific issues we've come across.

FYI: NPM 3 was originally released in June, but it's only been out of beta since September 18th:
http://blog.npmjs.org/post/129378362260/npm-weekly-29-npm-3-out-of-beta-nick-out-of-the
3.3.3 is now considered the stable version.

**Comment by henrify** [comment]
Yeah, that is exactly why we are not upgrading anything ever to a new major release as early adopter.

**Comment by retlehs** [comment]
we can't document every single thing. like you said:

> This is not your fault and it has been much discussed in node/npm forums.

we can add notes to https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060. feel free to make a discourse thread with specifics. all of us (except @QWp6t) are on macs.
