### ISSUE TITLE
Global WordPress Variables inside of Blade

### ISSUE THREAD

**Issue by Log1x** [roots/sage#1786]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

Replace any `X` with your information.

---

**What is the current behavior?**

Attempting to access a global variable defined by WordPress inside of a blade such as $post, $wp_query, $shortcode_tags, etc. return undefined.

**What is the expected or desired behavior?**

For them to return their proper values without having to use $GLOBALS to scope them.

---

**Other relevant information:**

It appears getting any kind of global within' blade isn't possible right now without manually sharing them with for example:

```
    sage('blade')->share('review', $GLOBALS['review']);
    sage('blade')->share('location', $GLOBALS['location']);
    sage('blade')->share('options', $GLOBALS['options']);
    sage('blade')->share('post', $GLOBALS['post']);
    sage('blade')->share('shortcodes', $GLOBALS['shortcode_tags']);
    sage('blade')->share('_POST', $_POST);
```

I'm unsure if there is a cleaner method of doing this or something that can be written into the core implementation of Sage's use of blade to make this more user friendly.

Not only are you unable to scope global variables set by WordPress, but you also can not get variables such as $_GET and $_POST from within' the blade. While these would best be used outside of the view, I still feel as if it'd be necessary to have a way to call them. I have come across [this](https://laravel.com/docs/5.3/requests) in the Laravel docs that may be relevant but I'm unsure if it's already possible with the current implementation.

Not being able to access variables also causes issues with attempting to use Blade for something like:

```
class UserReview extends \Walker_Comment
{
  /**
   * Returns a styled user review.
   *
   * @param  array $comment
   * @param  int     $depth
   * @param  array $args
   * @return string
   */
    protected function html5_comment($comment, $depth, $args)
    {
        include(locate_template('templates/partials/comments-single-reviews.blade.php'));
    }
}
```

even when using `\App\template('templates/partials/comments-single-reviews.blade.php');` due to it not passing the variables like an `include` would. I tried pushing the variables into an array and passing it with `\App\template('templates/partials/comments-single-reviews.blade.php', $data);` as seen in the `template` function source code but was still unable to properly get the data.

I wasn't sure whether to call this a bug, feature request, or if it's simply user error (i.e. me not knowing how to use the implementation properly to get the results I want)-- but felt it should be brought up as Sage 9 nears Beta/Release and things like this will more than likely need to be documented to stop a swarm of confusion.

Thanks in advance, and thank you for everything you guys do. Sage 9 has been a real treat to use so far.

**Comment by kalenjohnson** [comment]
```
@php global $post @endphp
{{ $post->post_title }}
```
seems to work

This seems to be working as expected as well:
`@php dd($_GET) @endphp`
as does
`@php(dd($_GET))`

It seems like the only thing that causes an issue is trying to do `@php(global $post)`, something about unexpected `global`.

However, needing to call `global $post` here isn't different from any other WP theme or PHP code.

I feel like it's helpful to stress here as well, that the idea of using a templating engine is partially for enhanced syntax and style, but it's also because ideally you would get away from using globals for everything. Obviously WP still works off globals, but those are also maintained behind the WP functions.

Ideally if you have data that cannot be retrieved using built in WP functions, you can pass data to your particular template [here](https://github.com/roots/sage/blob/50bc9d8525d036822b183a647eed2361abf3c1f9/src/filters.php#L55).

For your issue with the Comment Walker, personally that's another thing I might try and avoid using in the future, personally, however I'm guessing that it would work if you include `\App\template_path('templates/partials/comments-single-reviews.blade.php', $data);`, rather than `\App\template()`.

Not going to close this right away, as it may generate some more ideas.

**Comment by Log1x** [comment]
`include \App\template_path(locate_template('templates/partials/comments-single-reviews.blade.php'));` worked a treat. Thank you very much.

As far as calling `global $post`-- what mainly caused my confusion is in `sidebar.php` on Sage 8.5 I didn't need to call `$post` to fetch `$post->ID` for example `print_r(redux_post_meta('options', $post->id));` but in Sage 9 I do indeed have to.

My markup is indeed cleaner thanks to `sage('blade')->share()` though, that is a real treat to use.

Right you are on `$_GET` and $_POST` working-- I literally just tried it last night and was getting undefined when doing `{{ selected($_POST['sort-by'], $value, false) }}` but now it appears to work just fine. Bite my tongue.

**Comment by QWp6t** [comment]
```php
add_action('the_post', function ($post) {
    sage('blade')->share('post', $post);
});
```
That will make `$post` available in all of your partials, but it won't be available in top-level views (such as index.blade.php or page.blade.php).

Technically what's happening is that whenever you call `the_post()`, it's reassigning the `$post` variable to be loaded with subsequent views. Because we call `the_post()` from all top-level views, this means that any views they load (i.e., partials) will have the variable made available.

**Comment by QWp6t** [comment]
The above snippet has been integrated into Sage.
