### ISSUE TITLE
JavaScript changes require a page refresh within Browsersync session

### ISSUE THREAD

**Issue by retlehs** [roots/sage#1790]
we're aware of this issue, wanted to raise it on here so that y'all know we are working on a solution.

related topic:

https://discourse.roots.io/t/sage-9-js-doesnt-update-on-reload/8474

**Comment by andrewmartin** [comment]
Hi there, I'm hitting this issue still. I've tried following what was going on in that post, but I'm hitting a really annoying refresh loop if I make any changes to JS. Any suggestions on how to fix?

**Comment by andrewmartin** [comment]
Strangely, I changed

`"publicPath": "/app/themes/mysite",`

to

`"publicPath": "/wp-content/themes/mysite",`

And it seems to have fixed the problem. Thought I'd bring this up because I just used the default generator and didn't touch `config.json`, did I do some step wrong when I went through the CLI?

**Comment by retlehs** [comment]
the cli asked:

> Path to theme directory (e.g., /wp-content/themes/themename)

and instead of entering in the correct path it sounds like you accepted the default

by default sage uses `/app/themes/sage` as the `publicPath` as we're assuming you're using a bedrock install

please use https://discourse.roots.io/ for support

**Comment by pmascis** [comment]
I too was receiving the refresh loop @andrewmartin mentioned when changing any JS.
I accidentally had a trailing slash at the end of my theme name, which was causing the same thing.
i.e.
"publicPath": "/wp-content/themes/mysite/"
Instead of
"publicPath": "/wp-content/themes/mysite"

Sorry to revive this, just thought I'd mention in case anyone else makes the same silly mistake.

**Comment by builtbyvern** [comment]
I don't have a trailing slash and deal with this issue. It works 90% of the time but about twice an hour I get stuck in a reload loop where I have to literally empty out every file I have, hard refresh like 10x and then resave every file til it works again.

**Comment by knowler** [comment]
@builtbyvern 

I’ve collected a bunch of checks/fixes/solutions to Browsersync related issues on Discourse:
https://discourse.roots.io/t/sage-9-browsersync-not-updating-right/10648/11?u=knowler

The [Roots Discourse](https://discourse.roots.io) is the best place to find support.
