### ISSUE TITLE
Browsersync doesn't detect any change to any php file

### ISSUE THREAD

**Issue by derkjn** [roots/sage#1816]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

After the merge with `beta.2`, `Browsersync` doesn't detect any change to the php files either in `src` nor in `templates` folders.

**What is the expected or desired behavior?**

As before the latest update, `Browsersync` should automatically refresh the window when the templates or classes in the project are updated

---

## Bug report

**Please provide steps to reproduce, including full log output:**

Install a fresh copy of the theme.
Run `yarn run start`
Start changing your templates, you'll notice nothing happens and you have to manually refresh your browser.

**Please describe your local environment:**

WordPress version: 4.7.1

OS: 10.12.2

NPM/Node version: 3.10.8/6.9.1

**Where did the bug happen? Development or remote servers?**

Development

**Is there a related [Discourse](https://discourse.roots.io/) thread or were any utilized (please link them)?**

No

**Comment by derkjn** [comment]
After digging a bit, this behavior is caused by the newer version of the `browsersync-webpack-plugin`. Reverting back to `@0.1.1` fixes the issue temporarily.

**Comment by derkjn** [comment]
After digging a bit in the code I realized the issue is in the new version of the `browsersync-webpack-plugin`.

**Comment by QWp6t** [comment]
Can you test #1817 and let me know if that works for you?

**Comment by godofredoninja** [comment]
**I had the same problem and now I'll tell you what is a simple way to solve**
— It's my case this works for me even though it seems so stupid

* First you have to see which webpack version you have installed globally
* If you have version 1 then upgrade to [version 2](https://webpack.js.org/guides/installation/)

 👉 This solved my problem

**Comment by derkjn** [comment]
@QWp6t yes it's working now although I don't get the notifications from `browsersync` in the console anymore when the files are changed. Not that it matters since the browser refreshes anyway, but just thought it was worth mentioning.

@godofredoninja : I don't use `webpack` installed globally, I always use it locally depending on the project needs. In this case it was already version `2.2.0`

**Comment by Eljass** [comment]
@QWp6t I did the changes but still not refreshing? Steps I did:
- Add `delay: 500` to assets/build/webpack.config.watch.js,
- Add new dev dependencies to package.json,
- Remove yarn.lock,
- Remove node_modules folder,
- Run `yarn` in console.
- Run `yarn run start`

Did I miss something?

**Comment by derkjn** [comment]
How would you go about adding a third depth level to the watch list? For instance, I need to store my templates into `templates/partials/flexible-fields/*.php`.
If I add `templates/***/*.php` to the watch list it still doesn't pick up my changes.

**Comment by schrapel** [comment]
@QWp6t I'm experiencing the same on a fresh install of Sage. I do not have webpack installed globally

**Comment by QWp6t** [comment]
Do you have the issue with other files, such as JS or SCSS? Or is it just PHP?

If it happens with those files, then enable polling: https://webpack.js.org/configuration/watch/#watchoptions

Note that those watch options do not affect BrowserSync.

If it's only happening with PHP files, then it could be the `delay` or `debounce` setting in BrowserSync, especially if you're dealing with a filesystem shared with a VM. In that case, increase the `delay` specified in webpack.config.watcher.js: https://github.com/roots/sage/blob/master/assets/build/webpack.config.watch.js#L21

Alternatively, turn off safe writing if you're using IntelliJ (incl PhpStorm, WebStorm, etc) or set backupcopy to yes if you're using vim.

**PhpStorm** - https://www.jetbrains.com/help/phpstorm/2016.3/system-settings.html#d792972e131
Settings ▶︎ Appearance & Behavior ▶︎ System Settings ▶︎ Synchronization ▶︎ `safe write` (uncheck)

**vim** - http://vimdoc.sourceforge.net/htmldoc/options.html#'backupcopy'
`:set backupcopy=yes` 

This is all assuming you're using the latest beta (beta 2) and you made sure to update dependencies.

If you're still having issues after that, then I'd say to provide me with a reduced testcase (or give me more details of your environment and every step necessary for me to reproduce it on my own) and I'll reopen this issue, otherwise just take it to the forums @ https://discourse.roots.io/

**Comment by kirylpl** [comment]
@QWp6t I figure out in docs that 'Watching does not work with NFS and machines in VirtualBox.'
https://webpack.js.org/configuration/watch/#watchoptions
That's might be the issue?
