### ISSUE TITLE
Responsive Images on the Fly (like TimberImage)

### ISSUE THREAD

**Issue by koraysels** [roots/sage#1984]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [x] This is a feature request
- [ ] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [ ] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

## Feature Request

**Please provide use cases for changing the current behavior:**

It would be relevant I think to have a built-in Image Helper to save us developers time in developing a theme using Sage. I've worked with Timber before and kind of got used to syntax like this 
``{{ TimberImage(<imageRef>).src | resize(1280) }}`` right in my template files,
to resize the uploaded image to a size of my chosing.  

In My opinion it could be most beneficial for Sage to adopt something similar. Because then it would be even faster/easier to create a nice looking responsive theme.

What do you guys think?

**Comment by nicooprat** [comment]
Did you try https://github.com/syamilmj/Aqua-Resizer or https://github.com/deliciousbrains/wp-image-processing-queue? I finally decided to use the former last week.

These ~plugins are plug'n'play. What would you need as a better integration in Sage? Never used Timber.

**Comment by koraysels** [comment]
hmm that emaige processing queu plugin looks pretty promising! 

How do you use this in Sage ? Do you have a static function in you App controller for easy access using blade?

**Comment by nicooprat** [comment]
The second plugin can be installed from the official Wordpress plugins directory. The second one is just a PHP file that you can include in your theme. Both of them can be installed with composer I guess.

Using them is as simple as calling a function, so nothing special to do with Blaze. A directive could be a small enhancement though.

I had a lot of issues with WP Image Processing Queue though, so I finally chose Aqua Resizer, even if it looks less sophisticated.

Finally, both of them are compatible with image compressing plugins, because they internally use the official Wordpress functions. The downside is that you can only use them with images from the WP media folder (not images from your theme assets for example).

**Comment by webstractions** [comment]
Since version 4.4, WordPress handles responsive images in the background. It is up to the theme developer to define attributes for `srcset` and `sizes` via filters. Once set, all the magic happens automatically every time a user uploads an image. IMO, having Blade (a template engine) do this type of work for you is beyond its scope.

**Comment by nicooprat** [comment]
You can indeed define some custom dimensions, one time and for all, and it applies for all uploaded images. So on large websites you can end up with a lot of space used for nothing, plus the backoffice begins to slow down on every image upload. Querying image format right from the theme allows more modular usage and scales better.

I don't think it should be added in Blade by default, but I do think Sage could integrate this, as it integrates Blade (and even adds a small directive like `@asset()`). It depends if it's meant to be just a toolkit, or some kind of a starter pack...

**Comment by webstractions** [comment]
> So on large websites you can end up with a lot of space used for nothing, plus the backoffice begins to slow down on every image upload.

This is happening automatically anyway. You are gonna get several images stuffed into the upload directory whether you use them or not. 

> Querying image format right from the theme allows more modular usage and scales better.

How do you handle small screens vs. larger screens? 2X retina versions? I just can't see something like Aqua Resizer handling this without a lot of logic dumped into your Blade file. 

The image processing queue looks promising though, just for throwing everything into a queue (which gets served on the next request). The queue plugin, in a roundabout way, does the same thing as WordPress does though. I could see a use for it on custom posts or galleries where you need something more than the defaults. 

At any rate, not sure if you need a Blade directive for any of these. You can create a static function in one of your controllers to handle the output. For instance, maybe a Project single that requires non-standard images

```php
<?php

namespace App;

use Sober\Controller\Controller;

class Project extends Controller
{
    public static function featuredImageSrc()
    {
        return ipq_get_theme_image( $post->post_id, array(
              array( 600, 400, false ),
              array( 1280, 720, false ),
              array( 1600, 1067, false ),
          ),
          array(
              'class' => 'project-banner'
          )
       );
    }
}
```
```blade
// views/project.blade.php

<div class="banner-wrap">
    {{ \App\Project::featuredImageSrc }}" 
</div>
```

**Comment by JulienMelissas** [comment]
Hey crew! Great discussion here but at this point we're sending emails to over 600 people every time. Sage won't be including a full responsive image solution out of the box (because everybody is going to want to do it differently, and the use cases are just way too broad) for now. And please do continue this discussion on [discourse](discourse.roots.io)!

**Comment by nicooprat** [comment]
Thanks. Following the discussion here: https://discourse.roots.io/t/responsive-images/10733
