### ISSUE TITLE
Unsupported use of @php directive

### ISSUE THREAD

**Issue by collegeman** [roots/sage#2012]
Dear amazing people at Roots;

I want to draw your attention to [this issue](https://github.com/laravel/framework/issues/22621) I reported in the Laravel project. It seems using the `@php` directive in what I've been calling the "single-tag-form" is no longer supported. The reason being that if there are any `@endphp` closing tags used in the same template, all of the content between the first `@php` and the last `@endphp` will be evaluated by the compiler to be of the same directive, resulting in unintended behavior, e.g., the intervening template code being printed to the screen.

Here's an example of the way you're using it:

https://github.com/roots/sage/blob/42db9f9c991202fda1e4939b556b85b979dab6cb/resources/views/layouts/app.blade.php#L2

This way that you're using the `@php` directive is functional, but only in isolation to the block-form that includes both the `@php` and `@endphp` tags.

**Comment by roots-ladybug** [comment]
Hi @collegeman,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).

**Comment by collegeman** [comment]
@roots-ladybug spanked me! 🐞

**Comment by elementalhub** [comment]
Also if you're using vscode and the Laravel Blade Snippets extension, emmet won't recognize anything after a @php() directive as "blade". Therefore snippets won't work and syntax highlighting is funny, for example comment syntax will be like 
`// foo`
instead of
 `{{-- foo --}}`

(Just in case anyone stumbles upon this as well and spent as much time as I figuring out why emmet wasn't working in my blade views.)
