### ISSUE TITLE
[QUESTION] Project Viability

### ISSUE THREAD

**Issue by danieluyo** [roots/sage#2040]
It's so cool integrate Blade and Illuminate in Wordpress. Thanks a lot, is awesome.

I have two questions about this project.

## Proyect size
Usually the size of one custom Wordpress theme is from 3MB ~ 10MB , but SAGE 279.6 MB in disk. This a lot. Naturally if remove node_modules (178.1 MB) we have one project with 100.9 MB. Its ok, but i don't know, for me is to much.

## Speed & performance
Wordpress is ugly (we all know), the speed in the site depends of how are created your queries. How is the "real speed" and the performance (i mean, in a production env)?

**Comment by roots-ladybug** [comment]
Hi @danieluyo,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).
