### ISSUE TITLE
BrowserSync permanent reload

### ISSUE THREAD

**Issue by Beatabout** [roots/sage#2053]
Hello. After placing picture or svg in ../assets/images/, browserSync start to reload, and doesn's stop untill reloding Ampps and  Yarn. Do not know how to fix it.

**Comment by roots-ladybug** [comment]
Hi @Beatabout,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).
