### ISSUE TITLE
Node v10.x Compatibility

### ISSUE THREAD

**Issue by runofthemill** [roots/sage#2067]
## Submit a feature request or bug report

- [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md)
- [ ] This is a feature request
- [x] This is a bug report
- [x] This request isn't a duplicate of an [existing issue](https://github.com/roots/sage/issues)
- [x] I've read the [docs](https://roots.io/sage/docs) and [NPM Debugging Guidelines post](https://discourse.roots.io/t/npm-debugging-guidelines-failed-npm-install-bower-install-or-gulp-build-read-this/3060) and followed them (if applicable)
- [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/c/sage) forums

---

**What is the current behavior?**

`yarn` fails as a some dependencies are not yet updated for Node v10.x

**What is the expected or desired behavior?**

All `yarn` commands work as expected

---

As not all dependencies have been updated, I am creating this issue for tracking, and can update as new issues are found.

Dependency | Current Version | Latest Version | Node v10.x Compatible?
-------------|-----------------|---------------|----------------
`node-sass`| `~4.8.3` | `4.9.0` | Yes
`webpack` | `~3.10.0` | `4.6.0` | No, but there are commits to `head` to fix

**Comment by knowler** [comment]
Updating to Webpack 4+ might be a bit challenging since there’s been a lot of compatibility issues with plugins. If the plan is still to move to Laravel Mix (#1868) — which would eliminate the need for a bunch of dependencies — it might be best to wait until JeffreyWay/laravel-mix#1495 is merged, which is also waiting for upstream issues to be resolved. And then you’d hope that all of Mix’s dependencies were compatible with Node 10.

**Comment by runofthemill** [comment]
@mmirus asked me to check if this is still an issue, and I cannot reproduce it using Node `v10.14.1`. I wish I had included more details in the original issue ¯\_(ツ)_/¯

Closing!
