### ISSUE TITLE
CSS maps don't work quite right

### ISSUE THREAD

**Issue by DragosMocrii** [roots/sage#2072]
If you add a rule such as 
```css
body {
   color:red;
}
```
to let's say, /assets/styles/common/_global.scss  then when inspecting the CSS rules in dev tools, the file where the code is referenced is bootstrap's reboot.scss file. I believe this is happening because of the optimizations that are happening with CSS, specifically removing duplicated rules. In this case, the body selector is first contained in the reboot.scss file, therefore the code I added later in _global.scss is simply injected in the former rule. Not sure if possible, but is there any solution to make the proper reference to the last source file where the rule was defined? (I assume one option would be to disable CSS optimizations)

**Comment by roots-ladybug** [comment]
Hi @DragosMocrii,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).
