### ISSUE TITLE
Undefined variables in searchform

### ISSUE THREAD

**Issue by eagle-design** [roots/sage#2101]
i have been installed it now.
in home page : 

```
"require": {
    "php": ">=7.1",
    "composer/installers": "~1.0",
    "illuminate/support": "~5.6",
    "roots/sage-lib": "~9.0.2",
    "soberwp/controller": "~2.1.0"
  },
  "require-dev": {
    "squizlabs/php_codesniffer": "^2.8.0",
    "roots/sage-installer": "~1.3"
  },
```
```
<form role="search" method="get" class="search-form" action="<br />
--
  | <b>Notice</b>:  Undefined variable: sf_action in <b>E:\laragon\www\wp\wp-content\uploads\cache\513ef1a697bb8293e37b1ab09b1fe70af501f195.php</b> on line <b>1</b><br />
  | ">


```

**Comment by roots-ladybug** [comment]
Hi @eagle-design,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).

**Comment by eagle-design** [comment]
I didn't have changed the codes !!

**Comment by darrenjacoby** [comment]
Strange, the variables are available in the view.

**Comment by eagle-design** [comment]
@darrenjacoby Did you install it now ? if not can you tell me your versions

**Comment by darrenjacoby** [comment]
I did, and I can replicate the issue. The variables being used in search_form and available in the view, but they are not pulling in for the search form for some reason. I will need to investigate more.

**Comment by mmirus** [comment]
Let's continue this over at #2105. Thanks!
