### ISSUE TITLE
Helpers not available in controllers

### ISSUE THREAD

**Issue by eddiemf** [roots/sage#2140]
Hello there, I'm not sure if this is actually a problem or just confusion caused by my lack of knowledge, but it makes sense for me that functions declared inside the `helpers.php` file (and every other file inside the `app` folder) should be also available inside controllers. As of right now they are only available inside templates, if I want to reuse functions in controllers I need to create them inside the `functions.php` file, which looks weird based on the app structure. 

As I've said, I'm not sure if this is a problem with Sage or maybe with the controller package, so can I have some guidance here on how to best solve this problem? 

Thanks a lot!

**Comment by roots-ladybug** [comment]
Hi @eddiemf,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).

**Comment by tedw** [comment]
For anyone else that comes across this, this worked for me `\App\helper_function_name`
