### ISSUE TITLE
Suggestion: Updating the Sage > Invalid PHP Version Error to correct minimum version

### ISSUE THREAD

**Issue by buckedup** [roots/sage#2166]
I know it's nitpicky, but currently the error when PHP is below the minimum requirement it simply states:

> You must be using PHP 7.1 or greater.

But in the documentation states the minimum is 7.1.3

_I recently told a new host the minimum was 7.1 so they installed 7.1.28... not sure if the theme should work at that version or not because 7.1.3 hasn't been installed yet, but if the theme truly is broken unless at least at 7.1.3 then I think the error should reflect that._

Sage4Lyfe!! 🙌

**Comment by roots-ladybug** [comment]
Hi @buckedup,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).

**Comment by garrettw** [comment]
28 > 3
just FYI

**Comment by buckedup** [comment]
![WxLVUgB](https://user-images.githubusercontent.com/47091127/56169438-1c943780-5fac-11e9-9741-b9f29194dc89.gif)
