### ISSUE TITLE
Custom JS for Admin panel not working

### ISSUE THREAD

**Issue by debabratakarfa** [roots/sage#2168]
Gist reference 
https://gist.github.com/debabratakarfa/2c54b2db6fd20db0269ba65b93de5f18

When I am checking Chrome Console at http://local.wordpress.test/wp-admin/index.php I am not able to see JS function running.

**Comment by roots-ladybug** [comment]
Hi @debabratakarfa,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).
