### ISSUE TITLE
Theme Localization problems

### ISSUE THREAD

**Issue by AleCss81** [roots/sage#2170]
Hi, I'm trying to add language files as explained in the [Sage docs](https://roots.io/sage/docs/theme-localization/). I have installed with Homebrew coreutils, findutils and gettext and I have run `yarn pot` but I'm still receiving this error on terminal:

```
xargs: xgettext: No such file or directory
error Command failed with exit code 127.
```
I have copied the code shown on [Theme localization](https://roots.io/sage/docs/theme-localization/) page.

I hope you can help me, thanks

**Comment by roots-ladybug** [comment]
Hi @AleCss81,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).

**Comment by stefanfisk** [comment]
To anyone who encounters this issue: Extending `make-pot` to support Blade templates is actually not that complicated. Here's an example  that compiles the views and runts the default extractor on them: https://github.com/pressbooks/pb-cli/commit/afe5bb1842dd1660076d657504871f1476b60084
