### ISSUE TITLE
404 errors on pages - custom post types 

### ISSUE THREAD

**Issue by gaz-obel** [roots/sage#2175]
I'm experiencing this issue still and realistically I need to use 'rewrite' => array('slug' => '//'), since I am wanting to rewrite the urls for my custom post types. It seems bizarre that this affects the pages and causes them to have a 404 error. Is there a fix for this which doesn't involve  removing 'rewrite' => array('slug' => '//')?

_Originally posted by @gaz-obel in https://github.com/roots/sage/issues/277#issuecomment-489052708_

**Comment by roots-ladybug** [comment]
Hi @gaz-obel,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).
