### ISSUE TITLE
Map core and plugin assets within webpack

### ISSUE THREAD

**Issue by huraji** [roots/sage#2191]
Hey there, is it possible to map and combine all the plugins and core assets within Sage webpack build? 

Aside the theme assets, I'm struggling to find a way to combine the crap enqueued by plugins and core. Let me know if this makes any sense for you.

**Comment by roots-ladybug** [comment]
Hi @huraji,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).
