### ISSUE TITLE
Bootstrap 4 Navbar Toggler Icon not showing

### ISSUE THREAD

**Issue by vincentsch** [roots/sage#2192]
I just installed Sage on a new project using `composer create-project roots/sage example-theme`.

Then I added a Boostrap 4 navbar to header.blade.php:

```
<nav class="navbar navbar-expand-lg navbar-light bg-light nav-primary">

  <a class="navbar-brand" href="{{ home_url('/') }}">{{ get_bloginfo('name', 'display') }}</a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	<span class="navbar-toggler-icon"></span>
  </button>

  @if (has_nav_menu('primary_navigation'))
	<div class="collapse navbar-collapse" id="navbarSupportedContent">
	{!! wp_nav_menu($primarymenu) !!}
	</div>
  @endif


</nav>
```

Result: Bootstrap 4 Navbar Toggler Icon is not showing because of those two lines in _variables.scss:

```
$navbar-dark-toggler-icon-bg: none;
$navbar-light-toggler-icon-bg: none;
```

This appears to be a fix for some older bug but instead introduces a new one.

Commenting out those two lines makes the problem go away.

**Comment by vincentsch** [comment]
#2017

**Comment by roots-ladybug** [comment]
Hi @vincentsch,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests (use the [Roots Discourse](https://discourse.roots.io/) to ask the Roots Community for help, or if you want the Roots Team to dedicate some time to your issue, we [offer our services](https://roots.io/services/) as well).
