### ISSUE TITLE
[10.0.0-dev] Tailwind Update

### ISSUE THREAD

**Issue by fabianwurk** [roots/sage#2215]
Tailwind needs an update for 10.0.0 branch - latest version is Tailwind 1.0.4.

**Comment by roots-ladybug** [comment]
Hi @fabianwurk,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests. Use [Roots Discourse](https://discourse.roots.io/) to ask the Roots community for help, or [hire someone from the community](https://discourse.roots.io/c/jobs).

**Comment by knowler** [comment]
I’ll refresh the dependencies once the PR is approved to merge. 👍 Thanks for the heads up.
