### ISSUE TITLE
"App" class can't be passed to Views

### ISSUE THREAD

**Issue by dueperdesign** [roots/sage#2274]
Hi all,
we're currently trying to implement a new theme based on sage, but there's an issue we've found in a recent project that we can't solve: we put this theme in our bedrock starter wp installation without the default create -project command, so we managed it as a composer package (with wpackagist) but when we activate it, it keeps going white screen with this error in the log:

`PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Class 'App' not found in /my-wp-path/web/app/uploads/cache/2957ac46ca503f62e53b6829399d16182e08fad0.php:17`

The problem seems to be the "App" class that can't be passed to the Views (where we called the App::method()), and we honestly can't find a solution around the web.

Anyone faced the same issue? Can you kindly help us?

**Comment by roots-ladybug** [comment]
Hi @dueperdesign,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests. Use [Roots Discourse](https://discourse.roots.io/) to ask the Roots community for help, or [hire someone from the community](https://discourse.roots.io/c/jobs).
