### ISSUE TITLE
Class 'App' not found

### ISSUE THREAD

**Issue by jonathanlaf** [roots/sage#2283]
## Description
Can't get Sage to install properly. 

## Steps to reproduce
1. Install Sage through composer or git
2. Activate

**Expected behavior:** Working homepage

**Actual behavior:** Empty homepage with errors

>  ( ! ) Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Class 'App' not found in /srv/www/domain.tld/current/web/app/uploads/cache/a1e3c48b0395f0adfcf4ce178f4dd567983a6e72.php on line 2
--

**Reproduces how often:** 100%

## Versions

Windows 10 Pro 1903
VirtualBox : 5.2.32
Vagrant : 2.2.4
Ansible : 2.7.5
Trellis : 1.0.3
Sage : 9.0.9
WSL : Ubuntu 18.04.2 LTS
WSL Node : 8.10.0
WSL NPM : 3.5.2
WSL Composer : 1.9.0
WSL PHP : 7.1.3

## Additional information

I also tried to downgrade my PHP version in trellis to 7.1 still not working.

**Comment by roots-ladybug** [comment]
Hi @jonathanlaf,

It looks like the issue template is missing from this issue. Please take a look at the [Contribution Guidelines](https://github.com/roots/guidelines/blob/master/CONTRIBUTING.md), which will tell you **exactly** what your ticket has to contain in order to be processable.

Please **do not** use the issue tracker for personal support requests. Use [Roots Discourse](https://discourse.roots.io/) to ask the Roots community for help, or [hire someone from the community](https://discourse.roots.io/c/jobs).
