### ISSUE TITLE
Class 'App' not found

### ISSUE THREAD

**Issue by jonathanlaf** [roots/sage#2284]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description
Can't get Sage to install properly. 

## Steps to reproduce
1. Install Sage through composer or git
2. Activate

**Expected behavior:** Working homepage

**Actual behavior:** Empty homepage with errors

>  ( ! ) Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Class 'App' not found in /srv/www/domain.tld/current/web/app/uploads/cache/a1e3c48b0395f0adfcf4ce178f4dd567983a6e72.php on line 2
--

**Reproduces how often:** 100%

## Versions

Windows 10 Pro 1903
VirtualBox : 5.2.32
Vagrant : 2.2.4
Ansible : 2.7.5
Trellis : 1.0.3
Sage : 9.0.9
WSL : Ubuntu 18.04.2 LTS
WSL Node : 8.10.0
WSL NPM : 3.5.2
WSL Composer : 1.9.0
WSL PHP : 7.1.3

## Additional information

I also tried to downgrade my PHP version in trellis to 7.1 still not working.

**Comment by Log1x** [comment]
Assuming you have ran `composer install` inside of Sage's directory, perhaps try clearing your cache located in `app/uploads/cache/`. 

Nonetheless, this is not a bug or issue directly with Sage and is better suited for the [Roots Discourse](https://discourse.roots.io/) if further help is needed.

**Comment by jonathanlaf** [comment]
Even when clearing the cache it's not working. I'm sorry to ask you, but why are you so confident it's not a bug and it's user related ? I destroyed my VM and local files so many time that the cache got rebuild every time I tried. Seriously I spent many hours making sure it was not my manipulation that cause the bug.

**Comment by Log1x** [comment]
What is your install / build step order for Sage?

This problem has been [mentioned](https://discourse.roots.io/t/controller-doesnt-work-when-installing-sage-based-theme-via-composer/10272/15) [multiple](https://github.com/soberwp/controller/issues/48) [times](https://github.com/roots/sage/issues/2094) and has to do with Controller. There should be plenty out there to debug it no matter your specific situation by searching:

```php
( ! ) Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Class 'App' not found in 
```

**Comment by jonathanlaf** [comment]
I've read the 3 you just sent me, none worked for me. And yes I know how to do a google search I already searched that particular error. 

If there's so many people talking about that error, it's not a bug, it's all people fault ? 

What are my steps, 

In /site/web/app/themes/ I ran :
rm -r ../uploads/cache
composer create-project roots/sage my-cool-theme
cd /my-cool-theme
composer install
yarn & yarn build

Wordpress Settings -> Activate the my-cool-theme

Go to the front page, and got error.

**Comment by dsturm** [comment]
Just for the hint: @jonathanlaf, the root in the mentioned error (/srv/www/domain.tld/current/web/app/) differs from the last mentioned steps (/site/web/app/themes/). Did you shortened / simplify it for your last comment?

**Comment by jonathanlaf** [comment]
Yes I shortened it since I was typing it from the top of my head..

**Comment by ZizZu94** [comment]
I have the same issue. Any update? Any one solved this bug?
-thanks

**Comment by RistoNiinemets** [comment]
I got this fixed by upgrading composer packages.

**Comment by sparkbold** [comment]
> I got this fixed by upgrading composer packages.

Could you elaborate which packages?

**Comment by abombelli** [comment]
In our case it had to do with PHP 7.4. When we switched back to PHP 7.3 the error did not pop up anymore.

**Comment by Stilmant** [comment]
Hello. I have also the issue on my website also when migrating  PHP to a newer version here 7.4. 
I'm using a plugin based on older version of Sage it seems but since I don't know about PHP it is hard to debug on my side. I'm not developing under composer. 

the faulty code is certainly a "user related" but the "user" is no more there
issue is resources/views/front-page.blade.php
`         <div id="cubsmap-service" 
               data-zoom='{!! App::GetOption("cc_gmap_zoom", 0) !!}' 
               data-lat='{!! App::GetOption("cc_gmap_lat", 0) !!}' 
               data-lng='{!! App::GetOption("cc_gmap_lng", 0) !!}' 
               data-markers='{!! FrontPage::MapPositions() !!}'>
          </div>`

Stack trace:
#0 /var/www/html/wp-content/themes/[oursite]/vendor/illuminate/view/Engines/PhpEngine.php(43): include()
#1 /var/www/html/wp-content/themes/[oursite]/vendor/illuminate/view/Engines/CompilerEngine.php(59): Illuminate\\View\\Engines\\PhpEngine->evaluatePath('/var/www/html/w...', Array)
#2 /var/www/html/wp-content/themes/[oursite]/vendor/illuminate/view/View.php(142): Illuminate\\View\\Engines\\CompilerEngine->get('/var/www/html/w...', Array)
#3 /var/www/html/wp-content/themes/[oursite]/vendor/illuminate/view/View.php(125): Illuminate\\View\\View->getContents()
#4 /var/www/html/wp-content/themes/[oursite]/vendor/illuminate/view/View.php(90): Illuminate\\View\\View->renderContents()
#5 /var/www/html/wp-content/themes/[oursite]/vendor/roots/sage-lib/Template/Blade.php(58): Illuminate\\View\\View->render()
#6 /var/www/html/wp-content/themes/[oursite] in /var/www/html/wp-content/uploads/cache/91c448e8663ee0a6aecbc2d4c451f96c9b8792c4.php on line 38

**Comment by catgofire** [comment]
> but since I don't know about PHP it is hard to debug on my side.

This is not the place for this question. Your association needs to hire a PHP developer.

**Comment by Stilmant** [comment]
Well. Seems I'm not alone to face the issue. Seems that, the plugins that where developed with **roots sage** in the past are facing an issue when the website is upgraded to newer version of PHP. PHP 7.4

So here it is a good place to ask the question:
- So it could be bad usage by developers working with the Sage in the past
- or an issue in Sage in older versions.  (usage of a now deprecated feature?, or similar ) 

In both case it could be interesting to document the reason here. (or on Sage side or what new in PHP 7.4 affecting the plugin)  because when you search google for that exact problem you end-up here in this place.

For your suggestion about PHP developer for my association, I would be that developer but seems I will have to ramp up quickly and installing a full development environment since upgrading composer package seems a way to go... but here no composer etc.. just sources code on production.   a classic :-D

**Comment by Stilmant** [comment]
So I've a resolution of my issue. 
Seems it has to do with namespace. why affecter in PHP 7.4 is maybe(?) due to get_declared_classes() unpredictability in PHP 7.4 'https://github.com/squizlabs/PHP_CodeSniffer/pull/3052'

So I explicitly named the class including it's namespace 
```
+               data-zoom='{!! \App\App::GetOption("cc_gmap_zoom", 0) !!}'
+               data-lat='{!! \App\App::GetOption("cc_gmap_lat", 0) !!}'
+               data-lng='{!! \App\App::GetOption("cc_gmap_lng", 0) `!!}'
```

Now certainly not the best approach but. I started learning PHP like today :D

**Comment by saskaak** [comment]
I encountered something similar to this after re-provisioning Homestead vagrant box, jumping from PHP 7.1 to PHP 7.4. After a lot of digging I found that the problem was an old version of VirtualBox and everything was fixed after updating to VirtualBox 6. See: https://github.com/laravel/homestead/issues/1219

**Comment by QWp6t** [comment]
Let's continue this conversation on the forum.

https://discourse.roots.io/
