### ISSUE TITLE
`vendor` directory concerns

### ISSUE THREAD

**Issue by retlehs** [roots/sage#2438]
we have docs in place to warn about blade files and [how to configure your webserver to block them](https://roots.io/docs/sage/9.x/installation/#server-configuration), but [someone recently raised the question](https://discourse.roots.io/t/how-are-you-deploying-this-so-that-the-vendor-folder-isnt-exposed-to-the-public/17925) about the `vendor` directory that is generated from composer

we're looking into adjusting our installation instructions so that we recommend installing acorn through bedrock, but we also need to account for scenarios where users have a sage theme on a non-composer/bedrock based install

we can't advise to block all `vendor` directories from the server config because WP core itself has files in a directory with the same name (https://github.com/WordPress/WordPress/tree/master/wp-includes/js/dist/vendor) - h/t @knowler 

* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)

**Comment by folbert** [comment]
FWIW: After the issue came up at Roots Discourse, I searched for a solution and found https://getcomposer.org/doc/06-config.md#vendor-dir which allowed med to move the theme-vendor-directory out of docroot and place it in its own directory alongside Bedrocks. I have tested it locally and so far it works without any issues.

Disclaimer: I don't know if its possible that a badly written package will have hard-coded an assumption that it resides in "vendor" or if there are other implications to the vendor-dir approach that I have overlooked.
