### ISSUE TITLE
Sage 9 dependencies are out of date

### ISSUE THREAD

**Issue by retlehs** [roots/sage#2466]
Sage 9 dependencies are out of date and have been causing issues for a while, especially if you're runner newer Node versions

We need to either release another update to Sage 9 with updated dependencies or officially end support for it. Using this issue to consolidate other issues and some Roots Discourse threads 

Sage 9 documentation also needs to be updated to mention the last supported Node version if we're ending support for it

## Related issues/PRs

* #2423 
* #2416  
* #2411 
* #2367
* #2323
* #2298
* #2213 

## Related Discourse topics

* https://discourse.roots.io/t/sage-depricated-ddependencies/18231
* https://discourse.roots.io/t/yarn-dependencies-outdated/18123

**Comment by tedw** [comment]
`css-loader` is also very out of date and breaks inline SVGs in CSS:
https://discourse.roots.io/t/fix-yarn-build-production-webpack-config-optimize-js-and-corrupted-svgs/18128/3

Example of issue https://github.com/TrySound/postcss-inline-svg/issues/65

**Comment by integrate-your-mind** [comment]
Related to #2367 
Please update  node-sass to  version 4.14.1, the current version that comes by default does not build properly anymore. It throws a huge error and when you update node-sass it stops.

**Comment by yansusanto** [comment]
Yes, I'm on node v14 and everything fails on build. Reinstalling node-sass doesn't help either.

**Comment by ninjatron** [comment]
Any updates on this? I followed installation guide, wasted a lot of time due to cryptic node errors, and ended up here. I see that Sage 10 is in beta, will it be released pretty soon, asking because I just wanted use this for my personal blog. Would rather wait if production version will be released pretty soon.

**Comment by Log1x** [comment]
Sage 10 is production-ready.

**Comment by ninjatron** [comment]
> Sage 10 is production-ready.

You sure? Documentation only refers to 9 and 8. Either way, with v9 and Node 12.x this issue exists. For the future reference.

**Comment by Log1x** [comment]
outside of docs, yes I'm sure.

**Comment by ninjatron** [comment]
Well, I tried installing with composer create-project roots/sage themename **dev-master** and the result is that, it will run through a different installation process (doesn't have option setup preferences) then it fails to include Bootstrap, then engine complains that I am missing bootstrap/cache. In the end, I used the v9, looking at errors more carefully, I noticed that node-sass v4.9.4 was problematic, it had troubles with Linux x64 claiming it was unsupported environment. They had some bindings that would supposedly make it work, knowing that it probably would not :), I opted for bumping up package.json required version 4.14.0 and hoped that version of node-sass would not break this version of sage. Fortunately it did not. Then it started throwing some missing file/folder issues. Running sudo chown -R daemon /opt/lampp/htdocs/personal/ (personal is the folder name for my wordpress installation) solved that issue as well. Now it works. 

For the people of the future TLDR, my OS is Ubuntu 20.04, I solved this issue by upgrading the node-sass version in package.json file in the theme folder. After that I needed to change the permissions of my wordpress installation.

**Comment by devotoare** [comment]
> Sage 10 is production-ready.

I'm sure it's been asked a billion times but I can't find on official release date. Is there one? Or any plans/timeline to share?

**Comment by retlehs** [comment]
**re: sage 10** we've got an announcement that the team has been collaborating on, and we'll be getting out an update as soon as we can. our main steps to a sage 10 release can be found here: **#2357** - but let's talk about sage 9 deps here!

* * *

as far as solving issues for sage 9 builds, node 10 still works. give this a shot:

```
nvm use 10
npm install -g yarn
yarn run build:production
```

we're open to the idea of updating the node and front-end dependencies of sage 9 for another release. please reach out to me if you're interested, and we can set aside some funds from the roots sponsors to do so. 

lately, our main goal has been trying to work on sage 10 and acorn docs

**Comment by ninjatron** [comment]
> we're open to the idea of updating the node and front-end dependencies of sage 9 for another release. please reach out to me if you're interested, and we can set aside some funds from the roots sponsors to do so.
> 
> lately, our main goal has been trying to work on sage 10 and acorn docs

As far as this issue is concerned, at least in my OS, simply updating node-sass version was the only needed thing. It didn't break anything and works fine. I think it is fair to not focus on v9 updates if you are about to release v10, which seems like the case.

**Comment by reidelliott** [comment]
I am currently out of the office with limited access to email until Monday, September 14.

If this is of an urgent nature please forward your request to support@1905newmedia.com.

On September 10, 2020 at 11:56 AM, ninjatron (notifications@github.com) wrote:



we're open to the idea of updating the node and front-end dependencies of sage 9 for another release. please reach out to me if you're interested, and we can set aside some funds from the roots sponsors to do so.

lately, our main goal has been trying to work on sage 10 and acorn docs


As far as this issue is concerned, at least in my OS, simply updating node-sass version was the only needed thing. It didn't break anything and works fine. I think it is fair to not focus on v9 updates if you are about to release v10, which seems like the case.

**Comment by Rvervuurt** [comment]
Node-sass 4.9.4 doesn't support 64-bit systems, so I have to manually go in and edit it to `"node-sass": "~4.14.1"` every time, otherwise I simply can't build the first time after setting up the theme.

This has been going on for a while now, so I figured I'd leave a comment for once! (or make an issue, if this didn't exist already)

**Comment by strarsis** [comment]
PR ready: https://github.com/roots/sage/pull/2572

**Comment by retlehs** [comment]
closed by #2572 and tagged `9.0.10`, thank you @strarsis 🙏
