### ISSUE TITLE
Head-explodingly slow on a regular-sized site.

### ISSUE THREAD

**Issue by MitchEff** [roots/sage#2564]
I'm not really sure what the deal is. We took a chance with Sage for one of our client sites, and after building in a few pages/fields/etc, it:

-  takes several minutes to load a page
- ~45 seconds to update CSS changes
- gets stuck in refresh loops regularly (resolved by cancelling and doing `yarn start` again)
- WP back-end ~works~ but the tab spinner is stuck loading forever
- Laptop fans sound like a jet engine the whole time it's running

I guess I have a couple questions:
a) Do people use this in production? On like, sites with 10-20 pages?
b) Is there anything I can do about this, or is it just sort of meant to be like this?

**Comment by MitchEff** [comment]
🙄

**Comment by joshuafredrickson** [comment]
[Yes, people use Sage in production.](https://roots.io/showcase/)

It sounds like there's something going on with your local environment, because what you're describing isn't normal in my experience. Although, you may be better served by starting a discussion on https://discourse.roots.io/ than opening an issue.
