### ISSUE TITLE
Sage 10: White screen with PHP errors

### ISSUE THREAD

**Issue by Awilson089** [roots/sage#2656]
* [x] I've read the [guidelines for Contributing to Roots Projects](https://github.com/roots/.github/blob/master/CONTRIBUTING.md)
* [x] This request isn't a duplicate of an existing issue
* [x] I've read the [docs](https://roots.io/documentation/) and followed them (if applicable)
* [x] This is not a personal support request that should be posted on the [Roots Discourse](https://discourse.roots.io/) community

## Description

At the moment when a PHP error occurs, it produces a white screen. The error is written to application.log but it would be helpful to have the error display on the screen. Another problem with this is that small errors that would usually let a site continue working completely disable the site. It would be good to have the error logging work in a similar way to Sage 9 or previous versions of Sage 10. 

Development is slow when you're having the check the log a lot and turning WP_DEBUG to false seems to have no effect. 

One further thing I noticed is that if you have an undefined variable, wrapping it in an `@if` still returns an undefined error.

Thanks for all your work on Sage so far. 

## Steps to reproduce

1. Install a fresh copy of the latest sage 10 dev
2. Write any sort of php which will deliberately return false or an undefined variable

**Expected behavior:** Show the error on screen or inline with the site

**Actual behavior:** White screen is displayed

**Reproduces how often:** 100%

## Versions

MacBook Pro (Mid 2015) – Catalina 10.15.7
Sage 10 (Latest dev)
NPM 5.6.0
Node 12.14.0
PHP 7.3.25
Laravel valet

**Comment by lukasz-gorski** [comment]
I'm having the same issues all over the time. Even Roots.io Soil plugin is crashing the Sage 10 and giving "white no errors" screen.

**Comment by QWp6t** [comment]
I believe for now you can get this working by defining `WP_ENV` or setting [`app.env`](https://github.com/roots/sage/blob/master/config/app.php#L31) to `development`.

If you want it to fallback on `WP_DEBUG`, you could change it to something like this.

```diff
-'env' => defined('WP_ENV') ? WP_ENV : env('WP_ENV', 'production'),
+'env' => defined('WP_ENV') ? WP_ENV : env('WP_ENV', WP_DEBUG ? 'development' : 'production'),
```

@Log1x [this is what's causing the issue](https://github.com/roots/acorn/blob/main/src/Roots/Acorn/Exceptions/Handler.php#L27-L33), right?

**Comment by Log1x** [comment]
yeah. perhaps we should add [something like this](https://github.com/roots/acorn/commit/d942dd9bf9c615ba4659921751e8c2496e5ccc70#diff-4195229c8f86dbd663263925272cf9e87f2f5a654144b252927d97e0c799aa9aL13-L19) back

**Comment by Awilson089** [comment]
@QWp6t Cheers, that seems to work.

**Comment by palicko** [comment]
I have the same issue with white screen on `Undefined variable` and similar small errors.
Can I somehow modify that error handling, so it is not that strict?

It's really troubling, because sometimes LIVE website starts to throw fatals just because of the small typo or forgotten condition.

Thanks

**Comment by artshostak** [comment]
Same issue, clean Bedrock/Trellis/Sage10 install just ends up in a white screen on first deploy to `staging`.
Everything appears to load but drops off right at the opening `<div id="app">` line.

@QWp6t's solution didn't work, likely because this is `staging` and not `production` environment right?

**Comment by Awilson089** [comment]
> Same issue, clean Bedrock/Trellis/Sage10 install just ends up in a white screen on first deploy to `staging`.
> Everything appears to load but drops off right at the opening `<div id="app">` line.
> 
> @QWp6t's solution didn't work, likely because this is `staging` and not `production` environment right?

Have you made sure `WP_DEBUG` is also set to true? It should at least show the error then rather than the white screen.

**Comment by tomimaen** [comment]
We are having major issues with the way Sage currently is handling the errors by creating every `Undefined variable` etc. into Exceptions - I get the idea behind this but especially with ACF Gutenberg Blocks I think that it is too aggressive. 

The reason for this is that since there does not seem to be any way to actually force the required fields on ACF Gutenberg Blocks, the clients adding content will skip some of the required fields (or add empty links and so on) which will cause Exceptions (and white page in production) instead of silently logging the error and continuing the rendering process.

At this point I would be satisfied if I could just disable the Exceptions on production environment completely as currently we have to go back to the Gutenberg Blocks already created and make them overly protective for missing variables etc. every time a client reports back to us that there is a white page spotted on the site.

**Comment by neverin772** [comment]
To add to this, using @QWp6t fix kicks sage 10 into development mode and php errors are thrown. However if you cause a php error via blade. Something like this : -

```
@php
{{segsegsegrserg////////*****//8sergegr}}
@endpphp
``` 
This will throw another whitescreen.

**Comment by MichaelSchober** [comment]
Same issue here, errors in the template (like described by @neverin772 ) cause a whitescreen on my server while on local development the error messages display correctly. I made sure that `WP_DEBUG` is set to true and that `WP_ENV` is set to development on both instances.

**Comment by apsolut** [comment]
not a single error until switched to development:
`'env' => defined('WP_ENV') ? WP_ENV : env('WP_ENV', 'development'),` inside /yourthemename/config/app.php

**Comment by retlehs** [comment]
this should now be resolved when you upgrade your version of acorn in sage (#2844)

**Comment by pouzarm** [comment]
I've not tried it in latest version of Sage 10 (maybe there is some fix for this problem.. but i don't think so).

This will maybe help someone who will find this ticket. Changing version of **Accorn to 2.0.0** not help with the fact that Accorn/Sage 10 **throws white screen on NOTICES, WARNINGS** in **production mode** because it sets `error_reporting(-1)`; on startup.

This may be problem when your website contains plugins with errors that triggers `NOTICES` and `WARNINGS`, because that plugins becomes broken. (I know it is not okay having errors in code.. but not everyone have time to report and wait for fixes of all minor bugs in foreign code... web development isn't sadly backend development).

Way how to disable this is to set **error_reporting** with values that you want after the Accorn bootloader is loaded..



> WP without Bedrock used:

```
add_action('after_setup_theme', function () {
    if (defined(WP_DEBUG) && !WP_DEBUG) {
        error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING);
    }
}, PHP_INT_MAX);
```

```
add_action('rest_api_init', function () {
    if (defined(WP_DEBUG) && !WP_DEBUG) {
        error_reporting(E_ALL & ~E_NOTICE & ~E_WARNING);
    }
}, PHP_INT_MAX);
```
