### ISSUE TITLE
Don't include Acorn out of the box, but treat it as a requirement

### ISSUE THREAD

**Issue by retlehs** [roots/sage#2768]
## Summary

[Acorn](https://github.com/roots/acorn) is a package that is bundled with Sage 10 to provide access to some Laravel components, such as Blade, but we shouldn't include Acorn as a Composer dependency from the theme itself

## Additional context

The ideal way to have Acorn installed on a WordPress site would be from the [site-level Composer dependencies](https://github.com/roots/bedrock/blob/master/composer.json)

If your WordPress site doesn't support installing Composer dependencies, then Acorn can be installed as a mu-plugin or regular WP plugin

## Next steps

1. Remove `acorn` dependency in `composer.json`
2. Add a required check for Acorn in `functions.php`
3. Add Acorn installation instructions to the README and WIP Sage 10 docs

**Comment by Kilbourne** [comment]
Should be documented that when Acorn is added  to site-level composer deps AND there's a  folder named _config_  at site-level folder ( like in Bedrock), then you should add sth like `add_filter("acorn/paths.config", function(){ return get_stylesheet_directory() . DIRECTORY_SEPARATOR . 'config'; });` otherwise Acorn will not load Sage config but Bedrock one

**Comment by dawidurbanski** [comment]
@Kilbourne since the idea is to encourage adding Acorn via site-level composer deps, then it should be resolved in Acorn core instead of telling people to alter Acorn config path every time they use it with bedrock :)

**Comment by retlehs** [comment]
#2827
