### ISSUE TITLE
Getting 404 error on pages

### ISSUE THREAD

**Issue by jahvi** [roots/sage#277]
Not sure why but I'm getting a page not found error on my pages using any custom permalink structure (it works fine with custom post types though) I tried refreshing the permalinks a few times but it didn't help, first time this happened to me could it be related to the htaccess file?

**Comment by gaz-obel** [comment]
I'm experiencing this issue still and realistically I need to use 'rewrite' => array('slug' => '//'), since I am wanting to rewrite the urls for my custom post types. It seems bizarre that this affects the pages and causes them to have a 404 error. Is there a fix for this which doesn't involve  removing 'rewrite' => array('slug' => '//')?
