### ISSUE TITLE
Deprecated: Method ReflectionParameter::getClass() is deprecated

### ISSUE THREAD

**Issue by simplenotezy** [roots/sage#2793]
## Versions

sage: 9.0.10
php: 7.4.22

**Comment by joshuafredrickson** [comment]
This is attributed to the use of Laravel 5.6 in `roots/sage-lib`, which is [no longer receiving updates](https://github.com/roots/sage-lib/issues/4#issuecomment-1021251113).

In order to update Sage 9 to something more PHP 7.4 and 8.0 friendly, refer to the link above and the associated PRs. For example, to update using the branch for the [Laravel 7 PR](https://github.com/roots/sage-lib/pull/8):

`composer.json`:
```
...
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/mcaskill/sage-lib.git"
    }
  ],
  "require": {
    "php": "^7.4|^8.0",
    "composer/installers": "~1.9",
    "roots/sage-lib": "dev-feature/laravel-7",
    ...
  },
...
```
