### ISSUE TITLE
Sage 10 tailwind css is not working without small addition to tailwind.config.js

### ISSUE THREAD

**Issue by distributev** [roots/sage#3159]
### Version

10

### What did you expect to happen?

Tailwind CSS, being the default CSS framework in Sage 10, should be correctly configured 

Without adding the below change to the tailwind.config.js I could not get TailwindCSS working properly. Once I added the small change TailwindCSS started to work fine.

```
/** @type {import('tailwindcss').Config} config */
const config = {
  content: ['./index.php', './app/**/*.php', './resources/**/*.{php,vue,js}', './resources/views/**/*.blade.php'],
  theme: {
    extend: {
      colors: {}, // Extend Tailwind's default colors
    },
  },
  plugins: [],
};

export default config;
```

**_'./resources/views/**/*.blade.php'_** is the thing I had to add

### What actually happens?

The content array in your Tailwind CSS configuration specifies the files where Tailwind should look for class names to include in the generated CSS.

In your current configuration, Tailwind is looking in:

The index.php file at the root of your project
All .php files in the app directory and its subdirectories
All .php, .vue, and .js files in the resources directory and its subdirectories
If you're using Tailwind CSS classes in your Blade files, you should include './resources/views/**/*.blade.php' in the content array. This will tell Tailwind to look for class names in all .blade.php files in the resources/views directory and its subdirectories.

After updating your configuration, make sure to rebuild your CSS. If you're using Laravel Mix, you can do this by running npm run dev or npm run watch in your terminal.

### Steps to reproduce

---

### System info

Latest Sage 10.

### Please confirm this isn't a support request.

Yes

**Comment by Log1x** [comment]
Can you double check that you are experiencing this behavior with the default configuration?

`./resources/**/*.{php,vue,js}` should already handle the blade files since they end with **.php**.

**Comment by dsturm** [comment]
Dear @distributev ,

the current config uses `./resources/**/*.{php,vue,js}`, which will look for `*.php` files - besides `.vue` and `.js`. But since a blade file is named `*.blade.php`, the pattern will match these files also.

It works fine and I assume there must be something else, which caused a failure on your side.

You also mention Laravel Mix - the current build process uses bud instead. Do you really use the current state of Sage 10?

**Comment by dsturm** [comment]
@distributev, I set up a [repo of Sage with your mentioned Announcement component](https://github.com/roots/sage/compare/main...dsturm:sage:tailnext-test), ran a `dev`and also a `build`task and still cannot reproduce your issue.

The component is hidden below the `md` breakpoint:

![CleanShot 2023-11-20 at 21 49 39@2x](https://github.com/roots/sage/assets/384815/8a4eb93e-7fae-4509-ac44-7e6af30994ca)

... and shown above:

![CleanShot 2023-11-20 at 21 49 33@2x](https://github.com/roots/sage/assets/384815/fcfce9f4-492e-412b-ad33-4e3286325aa7)


For me it looks, like your code misses some others steps. Can you give us a repo, where we can try to locate the issue? Otherwise, please look at the given [repo](https://github.com/dsturm/sage/tree/tailnext-test).

**Comment by distributev** [comment]
You are right now it is working for me too - it was probably a caching issue, I lost a lot of time.
