### ISSUE TITLE
Roots can not find CSS and JS files

### ISSUE THREAD

**Issue by plekter** [roots/sage#426]
Hello! I really like Roots and would love to tinker around but Ive gotten a small problem at hands. I have a fresh WP 3.3.2 installation and latest Roots cloned from here but after installation, it does not find the CSS and JS files declared in head.

I am not sure what the issue could be but Im sure Im not the only one. Anyone has any helpful information?

**Comment by wilbo** [comment]
I struggled with this for half a day...

I work with Mamp and I was always working from sub directories, until i learned creating a virtual host per site.
- Make sure you add a [virtual host](http://foundationphp.com/tutorials/vhosts_mamp.php) to your Mamp workflow. 
- Do [Roots 101](http://roots.io/roots-101/).

**Comment by matthisamoto** [comment]
I had a similar issue, and after doing everything in this thread, it still wasn't working. Then I noticed my .htaccess was a little... verbose. So the Permalinks flush does NOT completely overwrite your .htaccess, it appends the Wordpress section and rewrites only that section. If you had copied in an .htaccess file from another project due to a boilerplate situation, or had written in anything that might interfere, Permalinks flushing will not cure the problem. Clear the other stuff out and it should work. Did for me.

**Comment by snoopdouglas** [comment]
Might be worth mentioning that I came across this exact same problem, only the reason that the assets weren't appearing is that I hadn't yet `gulp`'d. Doh.
